name: 'Fork Sync'

on:
  schedule:
    - cron: '20 3 * * *' # 每天北京时间上午11点20执行
  workflow_dispatch: # 允许手动点击运行
    inputs:
      sync_test_mode:
        description: 'Use Test Mode?'
        type: boolean
        default: false

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v6
        with:
          ref: main
          persist-credentials: false

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main
          upstream_sync_repo: cmliu/edgetunnel
          test_mode: ${{ inputs.sync_test_mode }}
